[project]
name = "llmchain"
version = "0.1.0"
description = "LLMChain: A framework for building agents and LLM-powered applications."
authors = ["pari9p <behlpari4@gmail.com>"]
license = {file = "LICENSE"}
readme = "README.md"
requires-python = ">=3.8"

[tool.setuptools]
packages = ["llmchain"]
